### ISSUE TITLE
utf8 support?

### ISSUE THREAD

**Issue by nparslow** [trufanov-nok/shuf-t#2]
Hi,
shuf-t looks really great (I have a 15gig file that needs shuffling) , but I noticed that when I applied it to some French text, the unicode characters caused the number of lines to be miscalculated and lines to be cut and mixed.

I thought of trying to change this, but my C++ is very rusty, and I couldn't even compile the code. What command should I be using to compile it and what do you think of adding an encoding option?

Thanks,
Nick

**Comment by trufanov-nok** [comment]
Hey, I believe that I've fixed these problems in dev branch of source code (by switching from Qt text stream objects to standard C++buffered reading), but I didn't make up-to-date a binaries yet (bcs I want to remove Qt completely and stick with pure C++ + boost lib).
 Are you using win or Linux binaries? I'll try to update them asap.
Could you also share a piece of your data (few hundred lines must be enough) somewhere? 
Or we can try to fix your sourcecode compilation problems

**Comment by nparslow** [comment]
I'm on linux mint, here's some sample data (using the binaries):

https://github.com/nparslow/example-dependency-data/blob/master/datatest.out

the output that I get:
https://github.com/nparslow/example-dependency-data/blob/master/output.out

it seems like the accented characters have interacted with the line endings in some way

edit: oncompiling, I'm not sure of what I have to link, I tried a couple of basic g++ / gcc combinations without luck, but maybe I should be generating a makefile somehow?

**Comment by trufanov-nok** [comment]
Could you try [this](http://1drv.ms/1LyoDhR) binary? It's up-to-date dev branch build.

**Comment by nparslow** [comment]
no luck, the output appears the same -
I do get an odd result when I call diff though:

> diff output.out output3.out
> Binary files output.out and output3.out differ

even though:

> file output.out
> output.out: UTF-8 Unicode text
> file output3.out
> output3.out: UTF-8 Unicode text

I'm not sure if that gives a clue or just shows that there is an encoding problem.

**Comment by trufanov-nok** [comment]
Ok, I'll try to take a deeper look this evening.

**Comment by trufanov-nok** [comment]
It seems I sent you wrong binary (master branch). The zip file with the right one is now available via the same link. Please try it. It looks it works correctly with dataset sample provided.

**Comment by nparslow** [comment]
brilliant, new one works perfectly on the sample, thanks heaps, shuf-t makes things a lot easier  :+1:

**Comment by trufanov-nok** [comment]
Should be fixed now. Up-to-date binary is published [here](https://github.com/trufanov-nok/shuf-t/tree/master/binaries)
