### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by tullis** [trufanov-nok/shuf-t#4]
Hi,

Would it be possible to add some build instructions for shuf-t please, ideally for Linux?

I'm currently looking at running shuf-t on a Debian Wheezy machine, but I get an incompatible Glibc version when trying your currently published binary version.

```
shuf-t: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by shuf-t)
shuf-t: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by shuf-t)
```

Many thanks.

**Comment by trufanov-nok** [comment]
Good point, I should think about this.

**Comment by trufanov-nok** [comment]
I've added a simple Makefile to master branch. Could you try it?:

```
CXX = $(shell which g++)

ifneq ($(CXX),)

else
  CXX = clang++
  $(warning Using clang++)
endif

ifeq ($(CXX),)
  $(warning No compiler found)
  exit 1
endif

CFLAGS=-c -Wall -O3
LDFLAGS=
SOURCES=utils.cpp main.cpp shuf-t.cpp io_buf.cc
OBJECTS=$(SOURCES:=.o)
EXECUTABLE=shuf-t

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS) 
    $(CXX) $(LDFLAGS) $(OBJECTS) -o $@
%.cc.o: %.cc
    $(CXX) $(CFLAGS) $< -o $@
%.cpp.o: %.cpp
    $(CXX) $(CFLAGS) $< -o $@    
clean:
    rm -f $(OBJECTS) $(EXECUTABLE)
install:
    cp $(EXECUTABLE) /usr/bin/$(EXECUTABLE)
```

**Comment by tullis** [comment]
Many thanks. I've tried it and it works perfectly .
It appears to work on Jessie as well, but I haven't tested it in depth.

The application works very well as well, shuffling around 100 million short lines in 29 seconds. Just what I was looking for.

**Comment by trufanov-nok** [comment]
Great!
