### ISSUE TITLE
sometime multiple lines are merged into a single line

### ISSUE THREAD

**Issue by tfurmston** [trufanov-nok/shuf-t#5]
I tried this on a dummy file with the following data, 

> 1 a
> 2 b
> 3 c
> 4 d
> 5 e
> 6 f
> 7 g
> 8 h
> 9 i
> 10 j
> 11 a
> 12 b
> 13 c
> 14 d
> 15 e
> 16 f
> 17 g
> 18 h
> 19 i
> 20 j

and it seems that sometimes (not all of the time) there are multiple lines joined together. For instance, I once got the following output,

> 4 d
> 1 a
> 18 h
> 6 f
> 17 g
> 12 b
> 13 c
> 3 c
> 15 e
> 20 j14 d
> 8 h
> 16 f
> 19 i
> 9 i
> 7 g
> 10 j
> 5 e
> 11 a
> 2 b

**Comment by trufanov-nok** [comment]
I'll take a look into that

**Comment by trufanov-nok** [comment]
It seems that it concatenates the last line with the random line if there is no return caret char at the end of file. So fast fix would be to add a new empty line to the end of your data file.
Still that's unexpected behavior for end user and should be treated as bug. I'll try to fix it soon.

**Comment by tfurmston** [comment]
I see. That makes sense. I did wonder why it was just one instance of two lines getting merged. 

Thanks for the quick response.
