### ISSUE TITLE
Alternate location for temp files

### ISSUE THREAD

**Issue by rspeer** [trufanov-nok/shuf-t#7]
I'd like to use `shuf-t` to shuffle some large files that I have on an external hard disk. I notice that it's using unreachable files in `/tmp` to store its input. But `/tmp` lives on my root partition, which is a small SSD.

Similar tools like `sort` allow specifying a different temp directory. Would it be possible to let `shuf-t` allow the same thing?

**Comment by trufanov-nok** [comment]
Good idea. Will check after my vacation ends.

**Comment by trufanov-nok** [comment]
I've added `--tempfile` option and linux binary. Could you check?

**Comment by rspeer** [comment]
It doesn't look like it's working. If I pipe text on stdin, it creates the temp file, but it stays at 0 bytes, and meanwhile space keeps being used up on my root partition.

**Comment by trufanov-nok** [comment]
Are you sure? Just tried it with stdin and it worked as expected.
Pls make sure that you're using right version.`shuf-t -v` should return 1.2.3. Do you check disk size changes with `df`? Checking via file manager like Dolphin may have delay in displaying changes. Also many processes could try to read/write small amount of data in your system drive.  Such noise could mislead if you're experimenting with small amount of data. For example, less than usual i/o buffer size (4~16kb).
